using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using AttackSkill.UI;
using UnityEditor;
using UnityEngine;

namespace AttackSkill.Editor.UIBinding
{
    /// <summary>
    /// 根据 Spec 生成 View 的 partial 绑定字段，并同步到 Prefab。
    /// </summary>
    public static class UIBindingCodeGenerator
    {
        const string GenFolder = "Assets/Scripts/UI/Views/Generated";
        const string PrefabFolder = "Assets/Prefabs/UI";

        [MenuItem("工具/UI/生成绑定代码", false, 50)]
        public static void GenerateAll()
        {
            if (!AssetDatabase.IsValidFolder("Assets/Scripts/UI/Views/Generated"))
            {
                if (!AssetDatabase.IsValidFolder("Assets/Scripts/UI/Views"))
                {
                    AssetDatabase.CreateFolder("Assets/Scripts/UI", "Views");
                }

                AssetDatabase.CreateFolder("Assets/Scripts/UI/Views", "Generated");
            }

            int n = 0;
            foreach (var spec in UIBindingSpecCatalog.All)
            {
                WriteGeneratedFile(spec);
                n++;
            }

            AssetDatabase.Refresh();
            Debug.Log($"[UIBinding] 已生成 {n} 个绑定文件 → {GenFolder}");
            EditorUtility.DisplayDialog("UI 绑定", $"已生成 {n} 个 *.Bindings.g.cs", "确定");
        }

        [MenuItem("工具/UI/同步绑定到 Prefab", false, 51)]
        public static void SyncAllPrefabs()
        {
            int ok = 0;
            int miss = 0;
            var log = new StringBuilder();
            foreach (var spec in UIBindingSpecCatalog.All)
            {
                string path = ResolvePrefabPath(spec);
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (prefab == null)
                {
                    log.AppendLine($"! 缺少 Prefab {path}");
                    miss++;
                    continue;
                }

                if (SyncPrefab(prefab, spec, log))
                {
                    ok++;
                }
            }

            AssetDatabase.SaveAssets();
            Debug.Log($"[UIBinding] 同步 Prefab {ok} 成功 / miss={miss}\n{log}");
            EditorUtility.DisplayDialog("UI 绑定", $"同步完成：{ok} 个 Prefab。\n详见 Console。", "确定");
        }

        [MenuItem("工具/UI/生成并同步绑定", false, 52)]
        public static void GenerateAndSync()
        {
            GenerateAll();
            SyncAllPrefabs();
        }

        static void WriteGeneratedFile(UIBindingViewSpec spec)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// 由「工具/UI/生成绑定代码」生成，请勿手改。");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine();
            sb.AppendLine("namespace AttackSkill.UI");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {spec.ClassName}");
            sb.AppendLine("    {");
            sb.AppendLine("        [Header(\"UI Bindings (generated)\")]");

            foreach (var f in spec.Fields)
            {
                string typeName = GetTypeName(f.ComponentType);
                if (f.CollectAll)
                {
                    sb.AppendLine($"        [SerializeField] {typeName}[] {f.FieldName};");
                }
                else
                {
                    sb.AppendLine($"        [SerializeField] {typeName} {f.FieldName};");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string outPath = $"{GenFolder}/{spec.ClassName}.Bindings.g.cs";
            File.WriteAllText(outPath, sb.ToString(), Encoding.UTF8);
        }

        static string ResolvePrefabPath(UIBindingViewSpec spec)
        {
            if (!string.IsNullOrEmpty(spec.PrefabPath))
            {
                return spec.PrefabPath.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase)
                    ? spec.PrefabPath
                    : $"{spec.PrefabPath}.prefab";
            }

            return $"{PrefabFolder}/{spec.PrefabName}.prefab";
        }

        static string GetTypeName(Type t)
        {
            if (t == typeof(RectTransform))
            {
                return "RectTransform";
            }

            if (t.Namespace == "UnityEngine.UI")
            {
                return t.Name;
            }

            return t.FullName;
        }

        static UIBase FindOrAddView(GameObject root, string className, StringBuilder log)
        {
            var all = root.GetComponents<MonoBehaviour>();
            for (int i = 0; i < all.Length; i++)
            {
                if (all[i] != null && all[i].GetType().Name == className)
                {
                    return all[i] as UIBase;
                }
            }

            Type viewType = null;
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();
            for (int a = 0; a < assemblies.Length; a++)
            {
                viewType = assemblies[a].GetType($"AttackSkill.UI.{className}");
                if (viewType != null)
                {
                    break;
                }
            }

            if (viewType == null || !typeof(UIBase).IsAssignableFrom(viewType))
            {
                return null;
            }

            var added = root.AddComponent(viewType) as UIBase;
            if (added != null)
            {
                log?.AppendLine($"  + {className} 已自动挂到根节点");
            }

            return added;
        }

        public static bool SyncPrefab(GameObject prefabRoot, UIBindingViewSpec spec, StringBuilder log)
        {
            string path = AssetDatabase.GetAssetPath(prefabRoot);
            var root = PrefabUtility.LoadPrefabContents(path);
            try
            {
                var view = FindOrAddView(root, spec.ClassName, log);
                if (view == null)
                {
                    log?.AppendLine($"! {spec.PrefabName}: 无 {spec.ClassName} 组件（且无法自动挂载）");
                    return false;
                }

                var so = new SerializedObject(view);
                var transforms = root.GetComponentsInChildren<Transform>(true);
                int wired = 0;

                foreach (var field in spec.Fields)
                {
                    var prop = so.FindProperty(field.FieldName);
                    if (prop == null)
                    {
                        log?.AppendLine($"  ? {spec.ClassName}.{field.FieldName} 字段不存在（请先生成代码并编译）");
                        continue;
                    }

                    if (field.CollectAll)
                    {
                        var list = new List<UnityEngine.Object>();
                        for (int i = 0; i < transforms.Length; i++)
                        {
                            if (transforms[i].name != field.NodeName)
                            {
                                continue;
                            }

                            var c = transforms[i].GetComponent(field.ComponentType);
                            if (c != null)
                            {
                                list.Add(c);
                            }
                        }

                        prop.arraySize = list.Count;
                        for (int i = 0; i < list.Count; i++)
                        {
                            prop.GetArrayElementAtIndex(i).objectReferenceValue = list[i];
                        }

                        if (list.Count > 0)
                        {
                            wired++;
                        }
                        else
                        {
                            log?.AppendLine($"  ! {spec.PrefabName}: 未找到节点 {field.NodeName}[]");
                        }
                    }
                    else
                    {
                        Component found = null;
                        for (int i = 0; i < transforms.Length; i++)
                        {
                            if (transforms[i].name != field.NodeName)
                            {
                                continue;
                            }

                            found = transforms[i].GetComponent(field.ComponentType);
                            if (found != null)
                            {
                                break;
                            }
                        }

                        prop.objectReferenceValue = found;
                        if (found != null)
                        {
                            wired++;
                        }
                        else
                        {
                            log?.AppendLine($"  ! {spec.PrefabName}: 未找到 {field.NodeName}:{field.ComponentType.Name}");
                        }
                    }
                }

                so.ApplyModifiedPropertiesWithoutUndo();
                PrefabUtility.SaveAsPrefabAsset(root, path);
                log?.AppendLine($"  ✓ {spec.PrefabName} 绑定 {wired}/{spec.Fields.Length}");
                return true;
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }
    }
}
